export default {
  FETCH_MY_CHARACTERS: 'FETCH_MY_CHARACTERS',
  FETCH_CHARACTER: 'FETCH_CHARACTER',
  CREATE_CHARACTER: 'CREATE_CHARACTER',
  UPDATE_CHARACTER: 'UPDATE_CHARACTER',
  SWITCH_CHARACTER: 'SWITCH_CHARACTER',
  REMOVE_CHARACTER: 'REMOVE_CHARACTER',
  RESET: 'RESET',
};
