export default {
  knight: 'knight',
  cleric: 'cleric',
  ranger: 'ranger',
  druid: 'druid',
  alchemist: 'alchemist',
  wizard: 'wizard',
  demoniac: 'demoniac',
  heretic: 'heretic',
  deathKnight: 'deathKnight',
  necromancer: 'necromancer',
  overlord: 'overlord',
  warlock: 'warlock',
  barbarian: 'barbarian',
  battleMage: 'battleMage',
  beastmaster: 'beastmaster',
  witch: 'witch',
  planeswalker: 'planeswalker',
  elementalist: 'elementalist',
};
