export default {
  AUTHORIZE: 'AUTHORIZE',
  LOGOUT: 'LOGOUT',
  FETCH_PROFILE: 'FETCH_PROFILE',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  FETCH_SETTINGS: 'FETCH_SETTINGS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
};
