export default {
  AUTHORIZE: 'AUTHORIZE',
  FETCH_PROFILE: 'FETCH_PROFILE',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  FETCH_CHARACTER: 'FETCH_CHARACTER',
  CREATE_CHARACTER: 'CREATE_CHARACTER',
  UPDATE_CHARACTER: 'UPDATE_CHARACTER',
  REMOVE_CHARACTER: 'REMOVE_CHARACTER',
  LOGOUT: 'LOGOUT',
};
